# Generated by Django 2.1.7 on 2019-03-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='what_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
