# Generated by Django 2.1.7 on 2019-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_what_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='what_time',
            field=models.TimeField(default=''),
        ),
    ]
