# Generated by Django 2.1.7 on 2019-03-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190322_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='what_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
