# Generated by Django 2.1.7 on 2019-03-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190323_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-created_on',)},
        ),
    ]
